version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily