name: Check library state

on: push

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check sources
        run: go vet ./...
      - name: Test sources
        run: go test ./...
      - name: Build sources
        run: go build ./...